"""drop irrigation_recommendations

Revision ID: 1bbc6a16cd9c
Revises: 3f34880223b3
Create Date: 2026-04-18 19:33:00.513714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1bbc6a16cd9c'
down_revision: Union[str, Sequence[str], None] = '3f34880223b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS irrigation_recommendations")
    op.create_foreign_key(None, 'farms', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'weather_readings', 'farms', ['farm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_readings', type_='foreignkey')
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_table('irrigation_recommendations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weather_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('water_amount_mm', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('duration_hours', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('method', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('irrigation_recommendations_ibfk_2')),
    sa.ForeignKeyConstraint(['weather_id'], ['weather_readings.id'], name=op.f('irrigation_recommendations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_irrigation_recommendations_id'), 'irrigation_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###
