"""unique constraint farm_id recorded_at weather_readings

Revision ID: 774627a55c7d
Revises: fecb6cfdf56f
Create Date: 2026-04-01 20:57:46.244098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774627a55c7d'
down_revision: Union[str, Sequence[str], None] = 'fecb6cfdf56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_weather_farm_recorded', 'weather_readings', ['farm_id', 'recorded_at'])   
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weather_farm_recorded', 'weather_readings', type_='unique')
    
    # ### end Alembic commands ###
