"""add_et_readings

Revision ID: e61ce02beb20
Revises: bddd4cef0237
Create Date: 2026-05-03 21:48:31.261866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61ce02beb20'
down_revision: Union[str, Sequence[str], None] = 'bddd4cef0237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('et_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('et_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'reading_date', name='uq_et_farm_date')
    )
    op.create_index(op.f('ix_et_readings_id'), 'et_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_et_readings_id'), table_name='et_readings')
    op.drop_table('et_readings')
    # ### end Alembic commands ###
