"""add soil_type to farms

Revision ID: fecb6cfdf56f
Revises: 
Create Date: 2026-04-01 17:56:44.036501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fecb6cfdf56f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('farms', sa.Column('soil_type', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('root_depth_cm', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('farms', sa.Column('growth_stage', sa.String(length=50), nullable=True))
    op.add_column('farms', sa.Column('planting_date', sa.Date(), nullable=True))
    op.add_column('farms', sa.Column('field_capacity_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('farms', sa.Column('wilting_point_pct', sa.Numeric(precision=5, scale=2), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_readings', type_='foreignkey')
    op.drop_index(op.f('ix_weather_readings_id'), table_name='weather_readings')
    op.alter_column('weather_readings', 'recorded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    # op.drop_column('weather_readings', 'farm_id')
    op.drop_constraint(None, 'irrigation_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'irrigation_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('irrigation_recommendations_ibfk_2'), 'irrigation_recommendations', 'weather_readings', ['weather_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('irrigation_recommendations_ibfk_1'), 'irrigation_recommendations', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_irrigation_recommendations_id'), table_name='irrigation_recommendations')
    op.alter_column('irrigation_recommendations', 'notes',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('irrigation_recommendations', 'recommended_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key(op.f('farms_ibfk_1'), 'farms', 'agronomists', ['agronomist_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.alter_column('farms', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('farms', 'wilting_point_pct')
    op.drop_column('farms', 'field_capacity_pct')
    op.drop_column('farms', 'planting_date')
    op.drop_column('farms', 'growth_stage')
    op.drop_column('farms', 'root_depth_cm')
    op.drop_column('farms', 'soil_type')
    op.drop_index(op.f('ix_agronomists_id'), table_name='agronomists')
    op.alter_column('agronomists', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
